### ISSUE TITLE
Android Emulator AVD

### ISSUE THREAD

**Issue by Rickzeer442** [needs-coffee/Whatsapp-android-to-ios-guide#3]
Hello, I Have a problem when I try to get msgstore.db. My device is not rooted so I follow this method : "https://gist.github.com/proxium/ee76c9a599a55e6d50b31e8159f66b39", but that's not worked.

So I follow your second method with the emulator android. Indeed, I created a Android virtual device (Pixel 5) without Google play. So in the setting, I logged in to google services, and I downloaded a Whatsapp apk and install on the AVD. But when I entered my phone number, the Whatsapp don't ask me to bakcup my messages. Same after, in the setting chat in Whatsapp, they never offer to recover his conversations with google drive, yet I did connect to my account Google. Do you have an idea ?

**Comment by Rickzeer442** [comment]
@needs-coffee If you have an idea please
![Capture d’écran 2022-01-25 105440](https://user-images.githubusercontent.com/98289183/150954323-8475e44e-555e-4ad9-91cd-e65369304197.png)

**Comment by needs-coffee** [comment]
Hi @Rickzeer442 
Could you check that the kitchen old device was backed up to google drive? And that a recent backup was done - you can force a backup on it if the last successful backup was a while ago. 
I had no problems getting the prompt for restore from backup but as far as I can remember the prompt only appears on first load of the app, if you close it you don't get asked to restore again .

You could delete the data for the apk on the virtual machine the way you would on a real android device and try again , or recreate the avd with another android version / emulated device 

I will have a play around with a spare phone number I have and the avd when I am home from work

**Comment by Rickzeer442** [comment]
Thank you for your answer! Yes on my real phone, I have a WhatsApp backup on Google drive. I will recreate the avd with another android version, and get back to you.

**Comment by Rickzeer442** [comment]
Hi @needs-coffee just to let you know that it works! I just changed my computer (my other computer had a firewall that blocked all Google services except Gmail).
Thanks again and sorry for the inconvenience

**Comment by needs-coffee** [comment]
> Hi @needs-coffee just to let you know that it works! I just changed my computer (my other computer had a firewall that blocked all Google services except Gmail).
> Thanks again and sorry for the inconvenience

No problem, glad it worked for you! 
Was working fine my end so your device must not have been able to access Google services
I will now close this issue
